apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
    - name: container-2
      image: busybox
      command:
        [
          'sh',
          '-c',
          'echo from hostPath container > /data/file.txt && sleep 3600',
        ]
      volumeMounts:
        - name: hostpath-storage
          mountPath: /data
  volumes:
    - name: hostpath-storage
      hostPath:
        path: /data
        type: DirectoryOrCreate
