apiVersion: v1
kind: Pod
metadata:
  name: pvc-test
  labels:
    app: myapp
spec:
  containers:
    - name: ctr-busybox
      image: busybox
      command: ['sh', '-c', 'echo PVC works > /data/file.txt && sleep 3600']
      volumeMounts:
        - name: vol-pvc
          mountPath: /data
  volumes:
    - name: vol-pvc
      persistentVolumeClaim:
        claimName: manual-pvc
