apiVersion: v1
kind: Pod
metadata:
  name: init-container-pod
  labels:
    app.kubernetes.io/name: myApp
spec:
  containers:
    - name: my-app-container
      image: busybox:1.37.0
      command: ['sh', '-c', 'echo "Application is running" && sleep 3600']
      resources:
        limits:
          memory: '128Mi'
          cpu: '500m'
  initContainers:
    - name: init-myservice
      image: busybox:1.37.0
      command:
        [
          'sh',
          '-c',
          'until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done',
        ]
