apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-hello-world
      image: virghiu/hello-world-app:1.0.0
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: '64Mi'
          cpu: '250m'
        limits:
          memory: '128Mi'
          cpu: '500m'
