apiVersion: v1
kind: Pod
metadata:
  name: app-with-sidecar-logging
  labels:
    app: sidecar-demo
spec:
  containers:
    - name: main-app
      image: busybox:1.37.0
      command:
        [
          'sh',
          '-c',
          'while true; do echo "logging" >> /var/log/main.log; sleep 1; done',
        ]
      resources:
        limits:
          memory: '250Mi'
          cpu: '500m'
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log

  initContainers:
    - name: log-processor
      image: busybox:1.37.0
      restartPolicy: Always
      command: ['sh', '-c', 'tail -F /var/log/main.log']
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log
  volumes:
    - name: shared-logs
      emptyDir: {}
