apiVersion: v1
kind: Pod
metadata:
  name: app-with-sidecar-logging-01
  labels:
    app: sidecar-demo-01
spec:
  containers:
    - name: main-app-01
      image: busybox:1.37.0
      command: ['sh', '-c']
      args:
        - |
          echo "Application starting..."
          while true; do
            echo "$(date) - App log entry" >> /var/log/main.log;
            sleep 5
          done
      resources:
        limits:
          memory: '250Mi'
          cpu: '500m'
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log

  initContainers:
    - name: log-processor-01
      image: busybox:1.37.0
      restartPolicy: Always
      command: ['sh', '-c']
      args:
        - |
          echo "Log processor initializing..."
          touch /var/log/main.log
          echo "Log processor initialized"
          sleep 2
          tail -f /var/log/main.log | while read line; do
            echo "[PROCESSOR] $line"
          done
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log
  volumes:
    - name: shared-logs
      emptyDir: {}
