apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: web
spec:
  containers:
    - name: container1
      image: nginx:alpine
      ports:
        - containerPort: 80
      env:
        - name: DATABASE_HOST # env variable called DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: cm1-db # configMap name
              key: DB_host # key in the configmap
