apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    type: first-secret
spec:
  containers:
    - name: ctr-busybox
      image: nginx:alpine
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
  volumes:
    - name: secret-volume
      secret:
        secretName: first-secret
